services:
  - type: web
    name: mlops-backend
    runtime: docker
    repo: https://github.com/An0maly404/DevopsMlopsFinal
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MLFLOW_TRACKING_URI
        value: https://dagshub.com/noah.hemon/DevopsMLopsProject.mlflow
      - key: MLFLOW_TRACKING_USERNAME
        value: noah.hemon
      - key: MLFLOW_TRACKING_PASSWORD
        value: 8cb0606103a4ffd2822ad447ce00fbff200b656a
    healthCheckPath: /health

  - type: web
    name: mlops-frontend
    runtime: docker
    repo: https://github.com/An0maly404/DevopsMlopsFinal
    branch: main
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://mlops-backend.onrender.com
