services:
  - type: web
    name: mlops-backend
    runtime: docker
    repo: https://github.com/An0maly404/DevopsMlopsFinal
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - fromGroup: mlops-secrets
    plan: free
    healthCheckPath: /health

  - type: web
    name: mlops-frontend
    runtime: docker
    repo: https://github.com/An0maly404/DevopsMlopsFinal
    branch: main
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://mlops-backend.onrender.com
