global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["mlops-backend-j5im.onrender.com"]
    scheme: https

remote_write:
  - url: https://prometheus-prod-65-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username: "3352002"
      password_file: /etc/secrets/grafana_remote_write_token
